SELECT p.ID AS "PROJECT_ID", p.NAME AS "NAME",
    EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE)) AS "MONTH_COUNT"
FROM project p
WHERE EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE)) = (
    SELECT MAX(EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE))) AS "MAX_MONTH_COUNT"
    FROM project
);
