ORDER BY c."NAME";

SELECT p.ID AS "PROJECT_ID",
    EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE)) AS "MONTH_COUNT"
FROM project p
WHERE EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE)) = (
    SELECT MAX(EXTRACT(MONTH FROM AGE(FINISH_DATE, START_DATE))) AS "MAX_MONTH_COUNT"
    FROM project
);
