SELECT
    p.ID AS PROJECT_ID,
    p.START_DATE,
    p.FINISH_DATE,
    SUM(w.SALARY * EXTRACT(month FROM AGE(p.FINISH_DATE, p.START_DATE))) AS PROJECT_COST
FROM
    project p
JOIN
    project_worker pw ON p.ID = pw.PROJECT_ID
JOIN
    worker w ON pw.WORKER_ID = w.ID
GROUP BY
    p.ID, p.START_DATE, p.FINISH_DATE
ORDER BY
    PROJECT_COST DESC;
